#!/bin/bash -e
#SBATCH -t 28-23:59
#SBATCH -c 1
#SBATCH --mem=12gb
#SBATCH -J TaxKing
#SBATCH --mail-type=begin,end,fail
#SBATCH --mail-user=peter.osborne@earlham.ac.uk
#SBATCH --constraint=intel

######NOTES######
#17/03/20
#This is the second script which should be run by the script TaxKing.sh in the
#same directory as this one. It will go to the directory which contains all the
#qc'eed fastq files produced by FastP. It will count how many there are, then
#use this information to populate the script which runs the jobs in the array.
#The first things it will do is echo and mail where the different variables are
#so you can check it is going to do what it is meant to.

#20/03/20
#See the TaxKing notes from this date for the changes there. The relevant bit
#here is that the centrifuge_hold variable should be made by reading from a file
#generated by TaxKing.sh

######SCRIPT######
cd $parent_directory
home_base=$(cat $working_directory/home_base_store.txt)
centrifuge_store=$(cat $working_directory/centrifuge_store.txt)
centrifuge_store=$(cat $working_directory/centrifuge_store.txt)
centrifuge_store=$(cat $working_directory/centrifuge_store.txt)
centrifuge_store=$(cat $working_directory/centrifuge_store.txt)
centrifuge_store=$(cat $working_directory/centrifuge_store.txt)
centrifuge_store=$(cat $working_directory/centrifuge_store.txt)
echo "The variables inherited from the TaxKing.sh script are as follows..."
echo "The directory this, and all the other scripts are to be found in is: '$home_base'"
echo "The directory which contained the original, non-qc'ed fastq files was: '$parent_directory'"
echo "The original, non-qc'ed fastq files are: $interleaved_fastqs"
echo "The directory which contains the qc'ed fastqs, where this script will operate is: '$working_directory'"
#Now you need to source the different softwares for the array script, so it doesn't need to do it every time itself
source package /tgac/software/testing/bin/kraken-2.0.7_beta
source package /tgac/software/testing/bin/metaphlan-2f1b17a1f4e9
source blast+-2.7.1
source diamond-0.9.10
source MEGAN-6.3.7
source package /tgac/software/testing/bin/gcc-5.3.0
source package /tgac/software/testing/bin/gcc-6.2.0
source package /tgac/software/testing/bin/centrifuge-1.0.4_6cc874e
#export $home_base || export home_base
#export $parent_directory || export parent_directory
#export $interleaved_fastqs || export interleaved_fastqs
#export $working_directory || export working_directory
variables_1=$(cat $working_directory/VARIABLE_STORE_1.txt) && echo "The centrifuge holding directory is to be made by reading from the file '$working_directory'/VARIABLE_STORE_1.txt, and is: '$variables_1'"
export $variables_1 || export variables_1
echo "Alright, here we go."
cd $working_directory
for f in *_qceed.fastq
do
  echo "One of the files which will be analysed is: '$f'"
done
filecount=$(ls *_qceed.fastq | wc -l)
sed '4,5s/PLACEHOLDER/'$filecount'/' $home_base/TaxArray_blank.sh > $home_base/TaxArray_run.sh
sleep 900 && sbatch $home_base/TaxArray_run.sh
