#!/bin/bash -eE
#SBATCH -t 01-12:30
#SBATCH -p ei-medium
#SBATCH -c 6
#SBATCH -J 2023-03-20_dRep_bins_trial
#SBATCH --mem=128gb
#SBATCH --mail-type=begin,end,fail
#SBATCH --mail-user=peter.osborne@earlham.ac.uk
#SBATCH -o /ei/.project-scratch/c/c33dfa31-8d66-4727-827b-ce9eb62d3237/2022-02-12_Paper_2-Chapter_2_Actual_taxonomy_and_function_as_well_as_mapping/strictest_bins/slurm_outputs/2023-03-20_dRep_bins_trial-%A.out
#SBATCH -e /ei/.project-scratch/c/c33dfa31-8d66-4727-827b-ce9eb62d3237/2022-02-12_Paper_2-Chapter_2_Actual_taxonomy_and_function_as_well_as_mapping/strictest_bins/slurm_outputs/2023-03-20_dRep_bins_trial-%A.err

#Written on 2023-03+20
#Written by Peter Osborne
#Written to be run on the NBI HPC

#Trial script to run dRep on 348 strict bins generated by Chris Q and Seb R, meant to compare them and then if any
#highly similar sets are found to pick the best representative for geach set.

#Trying to follow the relevant bit from https://peerj.com/articles/13084/#materials|methods

#This script can be found on the hpc at: /hpc-home/osbourne/Post-EI_scripts/2023-03-20_dRep_bins_trial.sh

#Failure catch function
failure_catch() {
  local lineno=$1
  local msg=$2
  printf "\nFailed at:\t$lineno\t$msg\n"
}
trap 'failure_catch ${LINENO} "$BASH_COMMAND"' ERR

#Setting fixed variables
export bins_inpdir="/ei/.project-scratch/c/c33dfa31-8d66-4727-827b-ce9eb62d3237/2022-02-12_Paper_2-Chapter_2_Actual_taxonomy_and_function_as_well_as_mapping/strictest_bins/fasta_files/all_strict_bins_isolate_assemblies_min_500bp_contigs_and_some_reference_genomes"
export top_outdir="${bins_inpdir}/dRep_output"

#Sourcing dRep 2.5.0
source package cfe4697f-e720-4a2b-a5a2-6fe645f39f34 #drep - 2.5.0

#Writing dRep function
execute_dRep () {
    inpdir="$1"
    outdir="$2"
    printf "Will run dRep on directory of 348 strict bins to obtain best representatives of any detected sets of highly similar files\n"
    printf "The input directory is $inpdir and the output directory is $outdir\n"
    dRep dereplicate -pa 0.95 "$outdir" -g "${inpdir}/*.fa"
    printf "Ran dRep on directory of 348 strict bins to obtain best representatives of any detected sets of highly similar files\n"
}

#Exporting dRep function
export -f execute_dRep

#Going to input directory
cd "$bins_inpdir"

#Executing the function
execute_dRep "$bins_inpdir" "$top_outdir"